version: "3.9"

services:
  # Create RabbitMQ container.
  # It is optional in case you don't have your RabbitMQ already.
  datamin-message-broker:
    image: rabbitmq:3-management-alpine
    container_name: datamin-message-broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for RabbitMQ GUI
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - datamin-rmq-network

  # Create RESTful API to populate messages in RabbitMQ.
  # This one is also optional in case you don't have your own data producer.
  datamin-producer:
    container_name: datamin-producer
    ports:
      - 3240:3240
    build:
      context: .
      dockerfile: Dockerfile-producer
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      QUEUE_NAME: ${QUEUE_NAME}
    restart: always
    networks:
      - datamin-rmq-network
    depends_on:
      - datamin-message-broker

  # Create container with message consumer.
  datamin-consumer:
    container_name: datamin-consumer
    build:
      context: .
      dockerfile: Dockerfile-consumer
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
      DATAMIN_API_URL: ${DATAMIN_API_URL}
      DATAMIN_API_CLIENT_ID: ${DATAMIN_API_CLIENT_ID}
      DATAMIN_API_CLIENT_SECRET: ${DATAMIN_API_CLIENT_SECRET}
      QUEUE_NAME: ${QUEUE_NAME}
      WORKFLOW_UUID: ${WORKFLOW_UUID}
    restart: always
    networks:
      - datamin-rmq-network
    depends_on:
      - datamin-message-broker

networks:
  # Create a new Docker network.
  datamin-rmq-network:
    driver: bridge
